### ISSUE TITLE
"Helper plugin fksdownloader is not available or invalid."

### ISSUE THREAD

**Issue by rrandall117** [fykosak/dokuwiki-plugin-fkshelper#1]
Dokuwiki Release 2015-08-10a "Detritus", attempting to use "FKStimer" (which does appear to function), I have the following constant error message being displayed:
"Helper plugin fksdownloader is not available or invalid."

I've re-installed the "fkshelper" a couple of times, but the error persists.

**Comment by cevro** [comment]
Thanks for report, it was forgotten to remove.

Fixed in [newest version](fykosak/dokuwiki-plugin-fkshelper/commit/6de3b52e110ca7ec47ccfac869d89a0e43c147a0).

**Comment by rrandall117** [comment]
Merci de développer tel un grand enfichable!!

J'ai juste vérifié qu'il travaille tout à fait avec Dokuwiki 2015-08-10a 
'Detritus' - et actualisé : https: // www.dokuwiki.org/plugin:fkstimer

Il serait GRAND si vous incluriez aussi KFSHelp dans le DokuWiki.org 
'Plugins' le site.

Remerciements!!

~ Richard C. Randall
rrandall@richardrandall.com
http://www.richardrandall.com
Skype: skype.richardrandall
Cell: (720) 840-1314
